// stateProvider
// urlRouterProvider
function config($stateProvider,$urlRouterProvider){
	$urlRouterProvider.otherwise('/home/index')
    $stateProvider
    .state("home",{
        url:"/home",
        templateUrl:"view/content.html"
    })
    .state("home.index",{
        url:"/index",
        templateUrl:"view/index.html",
        data:{
        	'title':'index',
        	'data':[1,2,3,4,5]
        },
        controller:'index'
    })
    .state("home.list",{
        url:"/list",
        templateUrl:"view/list.html",
        data:[1,2,3,4,5,6,7],
        controller:'list'
    })
    .state("home.product",{
        url:"/product",
        templateUrl:"view/product.html",
        controller:'product'
    })
    .state("home.about",{
        url:"/about",
        templateUrl:"view/about.html",
        controller:'about'
    })
    .state("user",{
        url:"/user",
        templateUrl:"view/content2.html"
    })
    .state("user.info",{
        url:"/info",
        templateUrl:"view/info.html"
    })
}
app=angular.module('app')
	.config(config)